---
slug: 2019/09/22/sentry
title: Sentryを使ってフロントエンドのエラーを確認する
date: 2019-09-21T15:26:09.132Z
description: Sentryを使ってフロントエンドのエラーを確認する
tags:
  - Sentry
  - Vue.js
headerImage: 'https://i.imgur.com/sN5BJB0.png'
templateKey: blog-post
---
# エラーの見逃しがよくあるある

自分で作ったWebアプリを何気なく触っていたらバックエンドのAPIと通信するaxiosの実装ミスで期待する動作になっておりませんでした。
レスポンスで200OK以外が返却された場合ERRORとなってしまうため、[README](https://github.com/axios/axios#handling-errors)によるとしっかりcatchしてあげる必要があったようです。

てっきりaxiosのresponseから取得できるstatuscodeでハンドリングするものだと思っていた・・・。

悪い例

```javascript
public async updateFileList() {
    const res = await axios.get(backendURL + 'data/upload/list');
    if (res.status === 200) { //statusでハンドリングしているが、200以外のstatusは設定されない・・
        this.uploadList = res.data.fileList;
    }
```

いい例

```javascript
const res = await axios.post(backendURL + 'convert/pdf/download', {
    uploadId: filePath,
    }, {responseType: 'blob'}).catch((err) => { //catchでエラーをつかむ
        if (err.response.status === 404) {
            this.$toasted.show('No File!!', options);
            throw new Error('PdfFileNotFound');
```

それはさておき、エラーが出ていても気が付かなかったのが問題ですので、何とかします。

## SentryをVue.jsで使ってみる

というわけでさっそく[Sentry](https://github.com/getsentry/sentry)を入れてみます。

